services:
  db:
    image: mariadb:latest
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MARIADB_USER=dev
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      - MARIADB_DATABASE=sample-app
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
volumes:
  db-volume: {}
