name: Vercel Branch Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on: pull_request

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --token=${{ env.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ env.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: |
          DEPLOY_URL=$(vercel deploy --token=${{ env.VERCEL_TOKEN }})
          echo "Deployed to $DEPLOY_URL"
          # Create DEPLOY_NAME from DEPLOY_URL removing the https:// part from it
          DEPLOY_NAME=$(echo $DEPLOY_URL | sed -e 's/https:\/\///g')
          echo "Deploy Name: $DEPLOY_NAME"
          DEPLOY_ALIAS="sample-app-gbrunacci-preview.vercel.app"
          vercel alias $DEPLOY_NAME $DEPLOY_ALIAS --token=${{ env.VERCEL_TOKEN }}
