name: Database Branch Merge
env:
  PLANETSCALE_BASE_DIRECTORY: .automation/pscale
  PLANETSCALE_SERVICE_TOKEN_ID: ${{secrets.PLANETSCALE_SERVICE_TOKEN_ID}}
  PLANETSCALE_SERVICE_TOKEN: ${{secrets.PLANETSCALE_SERVICE_TOKEN}}
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  db-branch-merge:
    name: Branch Setup
    runs-on: ubuntu-latest
    environment: Preview
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: Initialization
        id: init
        uses: actions/github-script@v6
        with:
          script: |
            console.log('Issue:', context.issue.number);
            if (!context.issue.number) {
              throw new Error('Branch deploys should only run in the context of a pull request');
            }

            core.setOutput('branchId', context.issue.number);

      - name: Check Branch Resources
        id: checks
        env:
          BRANCH_ID: ${{steps.init.outputs.branchId}}
        working-directory: ${{env.PLANETSCALE_BASE_DIRECTORY}}/
        run: |
          ./check-branch-diff.sh "preview-$BRANCH_ID"

