name: /remove command on preview environment
on:
  issue_comment:
    types: [created, edited, deleted]
jobs:
  remove-pr-environment:
    name: Remove Preview CMS
    # check if the comments come from pull request, exclude those from issue.
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    environment: Preview
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Initialization
        id: init
        uses: actions/github-script@v6
        with:
          script: |
            console.log('Issue:', context.issue.number);
            console.log('Comment:', context.event.comment.body);

            if (!context.issue.number) {
              throw new Error('Branch deploys should only run in the context of a pull request');
            }

            if (context.event.comment.body !== '/remove') {
              throw new Error('Comment body should be /remove');
            }
