name: /remove command on preview environment
on:
  issue_comment:
    types: [created, edited, deleted]
jobs:
  remove-pr-environment:
    name: Remove Preview CMS
    # check if the comments come from pull request, exclude those from issue.
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    environment: Preview
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Initialization
        id: init
        uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context, null, 2));

            if (!context.issue.number) {
              throw new Error('Branch deploys should only run in the context of a pull request');
            }

            if (context.payload.comment.body !== '/remove') {
              throw new Error('Comment body should be /remove');
            }

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `I am about to remove the environment`
            });